Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(LJ3D_joined.py:27276): Gdk-CRITICAL **: 15:35:42.157: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Started at: ---18341 days, 15:35:42.204952---
slurmstepd-cpu3: error: *** JOB 41184 ON cpu3 CANCELLED AT 2020-03-20T16:07:08 ***
